# Generated by Django 6.0.1 on 2026-02-09 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active')], default='DRAFT', max_length=20)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
            ],
        ),
        migrations.CreateModel(
            name='TaskMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('GUFICK', 'Gufick'), ('VLAD', 'Vlad'), ('VOVA', 'Vova'), ('MAX', 'Max')], default='GUFICK', max_length=30)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_person', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_task', to='task.task')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active')], default='DRAFT', max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'status': 'SUPERVLAD'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_team', to='task.team'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('GUFICK', 'Gufick'), ('VLAD', 'Vlad'), ('VOVA', 'Vova'), ('MAX', 'Max')], default='GUFICK', max_length=30)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_profile', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_team', to='task.team')),
            ],
        ),
    ]
