# Generated by Django 6.0.1 on 2026-01-27 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active')], default='DRAFT', max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active')], default='DRAFT', max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.team')),
            ],
        ),
    ]
