# Generated by Django 6.0.1 on 2026-01-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_target_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='target_person',
        ),
    ]
